# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import evaluator_pb2 as evaluator__pb2


class EvaluatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEvaluation = channel.unary_unary(
                '/Evaluator/GetEvaluation',
                request_serializer=evaluator__pb2.EvaluationRequest.SerializeToString,
                response_deserializer=evaluator__pb2.EvaluationDecision.FromString,
                )


class EvaluatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetEvaluation(self, request, context):
        """A simple RPC
        
        returns an evaluation of the given sample - Anomaly/Benign
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EvaluatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetEvaluation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEvaluation,
                    request_deserializer=evaluator__pb2.EvaluationRequest.FromString,
                    response_serializer=evaluator__pb2.EvaluationDecision.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Evaluator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Evaluator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetEvaluation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Evaluator/GetEvaluation',
            evaluator__pb2.EvaluationRequest.SerializeToString,
            evaluator__pb2.EvaluationDecision.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
